apiVersion: apps/v1
kind: Deployment
metadata:
  name: membership
  labels:
    app: membership
spec:
  selector:
    matchLabels:
      app: membership
  template:
    metadata:
      labels:
        app: membership
    spec:
      containers:
      - name: membership
        image: edenfed/kv-shop-membership:v0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  
