apiVersion: apps/v1
kind: Deployment
metadata:
  name: pricing
  labels:
    app: pricing
spec:
  selector:
    matchLabels:
      app: pricing
  template:
    metadata:
      labels:
        app: pricing
    spec:
      containers:
      - name: pricing
        image: edenfed/kv-shop-pricing:v0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  